import * as anchor from "@coral-xyz/anchor";

export default async function (provider: anchor.AnchorProvider) {
  // Set the provider (wallet + connection) for Anchor
  anchor.setProvider(provider);

  // Load your program using the workspace (auto-generated by Anchor)
  const program = anchor.workspace.MyAnchorProject as anchor.Program;

  console.log("🚀 Deploying the Anchor program...");

  try {
    // Example: Call an initialize instruction (if defined)
    const tx = await program.methods
      .initialize()
      .accounts({
        // These accounts must match the ones in your lib.rs instruction
        authority: provider.wallet.publicKey,
      })
      .rpc();

    console.log("✅ Program deployed successfully!");
    console.log("📦 Transaction signature:", tx);
  } catch (err) {
    console.error("❌ Deployment failed:", err);
  }
}
